export type Product = {
  slug: string;
  name: string;
  image: string;
  category: "Tiles & Stone Solutions" | "Wall Solutions" | "Grouts & Sealants" | "Waterproofing" | "Tools & Accessories";
  short?: string;
  categoryLabel?: string;
  applicationArea?: string;
  pack?: string;
  coverage?: string;
  surface?: string;
  color?: string;
  features?: string[];
  applications?: { no: number; application: string; size: string }[];
  pdf?: string;
  shadesImage?: string;
  applicationList?: string[];
};

export const products: Product[] = [
  { slug: "alpha", name: "HIR ALPHA", image: "/images/product/HIR-ALPHA.png", category: "Tiles & Stone Solutions", short: "HIR Alpha is developed according to the Indian and European standard that meets Type2T and C2T category parameters. HIR Alpha tile adhesive is recommended on flooring of tiles, marble, stone and for wall tiles.", categoryLabel: "Type2T , C2T", applicationArea: "Interior & Exterior", pack: "20 Kg", coverage: "0.54kg/Sq.Ft/3mm Thickness", surface: "Cement and Plaster", color: "Grey", features: ["Better Bonding than cement", "Better Pot Life than cement.", "Longer Adjustment time.", "Gel Base Technology.", "Easy to clean.", "More Flexible.", "100% silica sand."], applications: [{ no: 1, application: "Tile on Tile", size: "Any Size 800x800mm, 1000x1000mm" }, { no: 2, application: "Tiles on Floor", size: "Any Size 800x800mm, 1000x1000mm" }, { no: 3, application: "Tiles on Wall", size: "Any Size 600x600mm, vitrified tiles" }], pdf: "/api/public/pdf/alpha-technical-datasheet.pdf" },
  { slug: "beta", name: "HIR BETA", image: "/images/product/beta-2.png", category: "Tiles & Stone Solutions", categoryLabel: "Type3 , C2TE", applicationArea: "Interior & Exterior", pack: "20 Kg", surface: "Cement and Plaster", color: "Grey and White", features: ["Better Bonding.", "Better Pot Life.", "Easy to clean.", "More Flexible.", "100% silica sand."], applications: [{ no: 1, application: "Tile on Tile", size: "Any Size 800x800mm, 1000x1000mm, 1200x2400mm" }, { no: 2, application: "Tiles on Floor", size: "Any Size 800x800mm, 1000x1000mm, 1200x2400mm" }, { no: 3, application: "Tiles on Wall", size: "Any Size 600x600mm,800x800mm,1000x1000mm, 600x1200mm 12ft vitrified tiles" }, { no: 4, application: "Framing", size: "600x2400mm" }], pdf: "/api/public/pdf/beta-technical-datasheet.pdf" },
  { slug: "gamma", name: "HIR GAMMA", image: "/images/product/GAMMA Tiles.png", category: "Tiles & Stone Solutions", categoryLabel: "Type3T , C2TE", applicationArea: "Interior & Exterior", pack: "20 Kg", coverage: "0.52kg/Sq.Ft/3mm Thickness", surface: "Cement and Plaster", color: "Grey and White", features: ["Better Improved Bonding.", "Better Pot Life.", "Easy to clean.", "Improved quality.", "More Flexible.", "100% silica sand."], applications: [{ no: 1, application: "Tile on Tile", size: "Any Size 800x800mm, 1000x1000mm, 1200x2400mm" }, { no: 2, application: "Tiles on Floor", size: "Any Size 800x800mm, 1000x1000mm, 1200x2400mm" }, { no: 3, application: "Tiles on Wall", size: "600mmx2400mm, vitrified Tiles" }, { no: 4, application: "Framing", size: "600mmx2400mm Stone" }], pdf: "/api/public/pdf/gamma-technical-datasheet.pdf" },
  { slug: "delta", name: "HIR DELTA", image: "/images/product/DElta TItes.png", category: "Tiles & Stone Solutions", categoryLabel: "Type4TS1 , C2TES1", applicationArea: "Interior & Exterior", pack: "20 Kg", coverage: "0.495 kg/Sq.Ft/3mm Thickness", surface: "Cement and Plaster", color: "Grey and White", features: ["Better Improved Bonding.", "Better Pot Life.", "Long Open Time.", "Easy to clean", "Improved quality", "Better Deformation S1", "More Flexible", "No Shrinkage", "Sustains Heat Ageing", "100% silica sand"], applications: [{ no: 1, application: "Tile on Tile", size: "Any Size 800x800mm, 1000x1000mm, 1600x3200mm" }, { no: 2, application: "Tiles on Floor", size: "Any Size 800x800mm, 1000x1000mm, 1600x3200mm" }, { no: 3, application: "Tiles on Wall", size: "Any Size 1600x3200mm, vitrified tiles" }, { no: 4, application: "Framing", size: "Any Size 1200x3200mm Stone" }], pdf: "/api/public/pdf/delta-technical-datasheet.pdf" },
  { slug: "delta-plus", name: "HIR DELTA+", image: "/images/product/delta+_.png", category: "Tiles & Stone Solutions", categoryLabel: "Type4TS2 , C2TES2", applicationArea: "Interior & Exterior", pack: "20 Kg", coverage: "0.495 kg/Sq.Ft/3mm Thickness", surface: "concrete Cement, Plaster, blocks, Steel and Plywood.", color: "Grey and White", features: ["Dual Bonding Strength.", "Highly Flexible.", "High Deformation S2.", "Better Pot Life.", "Long Extended Open Time.", "Easy to clean.", "100% silica sand."], applications: [{ no: 1, application: "Tile on Tile", size: "Any Size 1600x3200mm" }, { no: 2, application: "Tiles on Floor", size: "Any Size 1600x3200mm" }, { no: 3, application: "Tiles on Wall", size: "Any Size 1600x3200mm, Vitrified tiles" }, { no: 4, application: "Framing", size: "Any Size 1200x3200mm Stone" }], pdf: "/api/public/pdf/delta-plus-technical-datasheet.pdf" },
  { slug: "flexi-plus", name: "HIR FLEXI+", image: "/images/product/Flexi +.png", category: "Tiles & Stone Solutions", categoryLabel: "R2TE", pack: "4 Kg", coverage: "50 Sq.Ft/1.5m Thickness/4 kg", color: "White", features: ["HIR FLEXI+ is two component systems.", "Simply mix 2 components Part-A and Part-B and apply thin coat on back of surface.", "1-2mm will be enough to adhere. Give support for just 60 minutes and that's it.", "HIR Flexi+ should be used within 20 minutes after mixing Part A and Part B. HIR Flexi+ can use to adhere", "Metal, Quartz, Glass, Aluminium, Wood, Marble Etc.", "Material is in two pack system. Use Part A and Part B in equal number."] },
  { slug: "back-tile-primer", name: "HIR BACK TILE PRIMER", image: "/images/product/Black-Tile-Primer.png", category: "Tiles & Stone Solutions", short: "Tiles, Marbles, Granites are like the focal points of a living or commercial space. The right selection can uplift the overall looks of any room or open space. However, the wrong tile, marble, granite installation process can shorten the lifespan of these stunning and equally expensive construction elements. Now a day's sizes of tiles, marbles and granites used are bigger and has property of low water absorption. This is the reason we need a product that can act as bridge between tiles, marbles, granites and adhesives or glue. A critical component of this process is Back Tile Primer. If you apply this product Back Tile Primer with tiles adhesive or glue for fixing the tiles, marbles, granites the performance will be enhanced. Once the space experiences changes in weather (summer, winter, rain), temperature, vibration, etc the tiles, marbles, granites will start unsticking from their placement, making them lose their position and crack over time.", pack: "1 Kg,5 kg", coverage: "50 Sq.Ft/2mm Thickness/5kg", color: "Buff", features: ["Water-resistant.", "Enhance the strength of tiles adhesive.", "Eco-Friendly product with longer life.", "Effective on multiple Application Area like Italian Marble, tiles and granites", "Japan & German Technology.", "It can be used on Marble Framing, Granite Framing."] },
  { slug: "block-jointer", name: "BLOCK JOINTER", image: "/images/product/HIR-BLOCK-JOINTER.png", category: "Wall Solutions", short: "Ready to use grey cement based non-shrink, self- curing mortar for fixing AAC blocks, Concrete blocks, fly ash bricks, Cement Mortar Blocks/Bricks, Cellular concrete blocks, Aerated Light weight blocks, Concrete hollow blocks, etc. HIR BLOCK JOINTER is cost-effective and water-resistance gives stronger and smoother finish.", applicationArea: "Interior & Exterior", pack: "40 Kg", coverage: "0.33kg/Sq.Ft/3mm Thickness", color: "Grey", features: ["100% Silica base Block Jointer.", "No shrinkage cracks at joints.", "No wastage during use like conventional cement mortar.", "Faster to apply due to good spreadable properties Better bond than conventional cement based mortar.", "Self-curing, No curing required after block work is done and hence making the construction faster than conventional based mortar.", "Only water to be added. Thinner jointing material Improved bond strength, compressive strength, tensile strength and overall masonry strength."] },
  { slug: "wall-putty", name: "HIR Wall Putty", image: "/images/product/Wall-putty.png", category: "Wall Solutions", short: "HIR WALL PUTTY is a white cement base fine powder modified with polymers and many other additives. It's new generation base technology gives high bonding strength, smooth and glossy finish.", applicationArea: "Interior & Exterior", pack: "40 Kg", coverage: "12 - 15 kg/Sq.Ft/2Coats | 8 - 12 kg/Sq.Ft/3Coats", color: "White", features: ["Good Workability.", "Superior Whiteness", "Does not require curing with water", "Good water resistance and can be applied on moist surface.", "Good Tensile Adhesion Strength, Compressive Strength and Flexural Strength.", "Resists growth of algae and fungi on wall.", "Gives, smooth glossy white finish ensure maximum paint spread and reduce consumption of paint."] },
  { slug: "white-cement", name: "HIR White Cement", image: "/images/product/White-cement.png", category: "Wall Solutions", categoryLabel: "Improved - C2TE", applicationArea: "Interior & Exterior", pack: "1/5Kg", coverage: "NA", color: "White", features: ["Better coverage", "Superior fineness", "Smooth finish", "High compressive strength"] },
  { slug: "sealant", name: "HIR SEALANT", image: "/images/product/Sealent.png", category: "Grouts & Sealants", short: "Sealant is formulated using high performance modified polymer that can be use as joint filler. It provides a strong bond with flexibility and elongation property which accommodates the cracks and joints in RCC, terraces, etc and provides a water resistant surface with aesthetic appearance. It has tendency to absorbs low movements vibrations and jerks for example lifts, elevators, etc.", pack: "1kg & 500gram", coverage: "NA", color: "White and Paintable", features: ["To fill all types of Gaps and joints.", "Non sagging use full for vertical and horizontal joints.", "Internal and External 3mm to 25mm joints.", "Bonds to most construction material and form waterproofing joints between RCC, concrete, Wood,Metal, Steel, Glass, Tiles, Marble, Stone, Mosaic, Etc.", "Sealing joint of wall, floor, balcony, around window or door frames, Lift and elevator gap filling."] },
  { slug: "tiles-grout", name: "HIR Tiles Grout", image: "/images/product/Tiles-grout.png", category: "Grouts & Sealants", pack: "1kg & 5KG", coverage: "NA", color: "Shades as shown", shadesImage: "/images/shades/SHADES.png", features: ["Smooth and Rich colour Grout", "Faster Drying Rate", "Stronger Than Ever Before", "Easy To Apply And Clean", "No Shade Variation", "Available In 12 Shades"] },
  { slug: "epoxy-grout", name: "HIR EPOXY GROUT", image: "/images/product/Epoxy.png", category: "Grouts & Sealants", short: "HIR R&D Team with latest technology and kindness of environment produce grout that stand time, wear and element with out of the box features. HIR introduce grout with versatile design, colour and user benefits.", pack: "1kg & 5KG", color: "Shades as shown", shadesImage: "/images/shades/Premium2.png", features: ["Available In 2 Part System Only", "Stainless Technology", "Extraordinary finish & Fine Texture", "Just Use Cloth to Remove from Application Area and Hands", "Acid And Alkaline Proof Colours", "Eco-Friendly", "Versatile Colours", "UV Resistant", "Internal and External Application", "Food Grade Certified"] },
  { slug: "sparkle-series", name: "HIR Sparkle Series", image: "/images/product/noimage.png", category: "Grouts & Sealants", features: ["Colour Richness", "Darkest Black Colour Ever", "Architect's Colours Collection", "Smoothest Ever", "Interior & Exterior Application Only", "Scratch Proof Technology", "More Coverage", "Easy To Apply And Clean", "Exclusive Product", "UV Resistant"] },
  { slug: "high-gloss", name: "HIR HIGH GLOSS", image: "/images/product/HIR_HIGH_GLOSS_M01.png", category: "Grouts & Sealants", shadesImage: "/images/shades/HIGHGLOSS.png", features: ["Exclusive Product", "3x Coverage", "Highest Glossiness Rate", "Zero Stain", "1.5 mm Depth is enough=More strength", "Specially Design For High Gloss Digital Tiles and Marble"] },
  { slug: "rock-series", name: "HIR ROCK SERIES", image: "/images/product/noimage.png", category: "Grouts & Sealants", short: "Developed and Designed By HIR R&D Team For Salt And Pepper Tiles", shadesImage: "/images/shades/ROCK.png", features: ["1st Time Ever In India", "Exclusive Product", "Indian Technology", "Developed and Designed By HIR R&D Team For Salt And Pepper Tiles", "Available In 6 Shades"] },
  { slug: "royal-o-seal", name: "Royal O Seal", image: "/images/product/HIR_Royal-O-Seal.png", category: "Waterproofing", short: "A Revolutionary product design specially to seal Tiles, Natural and Artificial Stone corner joints and make waterproof. Royal-O-Seal is two component material form strong joint sealer and gives aesthetic look. It keeps the corners joint clean and Hygiene. Available in various colour to match best with tiles or stone.", coverage: "100 running Ft/kg/3mm Cornering", color: "As shown", shadesImage: "/images/shades/royal.png", features: ["1st Time Ever In India", "Stainless Technology", "Resistance to Bacterial and Fungal Growth", "Acid and Alkaline Proof", "Eco-Friendly", "UV Resistance", "Waterproof", "Applicable Internal and External", "Hygienic"], applicationList: ["Bathroom", "Wash area", "Around Sanitaryware gaps", "Kitchen platforms", "Balcony", "Terrace", "Water tank etc..."] },
  { slug: "tiles-cleaner", name: "Tiles Cleaner", image: "/images/product/Tiles-cleaner.png", category: "Tools & Accessories", short: "HIR TILES CLEANER is ready to use cleaner, Clean the surface before & after application of epoxy grout, for removing stains of epoxy grout and tiles grout, minor efflorescence, difficult stain, from all types of tile like ceramic, porcelain & vitrified tile, natural-stone surfaces, glass mosaic & sanitary ware. Cleaning lime scale, moss and wax from stone, concrete, terrazzo and ceramics.", applications: [{ no: 1, application: "For Epoxy Grout Smooth Finish", size: "100ml in 11tr of water" }, { no: 2, application: "For Lime Scale, Effloresce, Difficult Stain From Tiles And Aged Grout", size: "Clean with water with 1:1 Proportion." }, { no: 3, application: "For Routine Tile & Sanitary Ware Cleaning.", size: "without mixing with water" }, { no: 4, application: "Mild Blemish Spots/Layers, Moss And Wax", size: "dilute two capful Tiles Cleaner with half bucket water" }] },
  { slug: "diamond-plus", name: "HIR DIAMOND PLUS", image: "/images/product/Dimond Plus.png", category: "Waterproofing", short: "HIR Diamond Plus is an admixture use to waterproof concrete during the construction stage. HIR Diamond Plus Entraps every single particle in concrete increase the free flow of concrete removing all air bubbles and fill all the gaps easily makes concrete cohesive, more intact and waterproof, and increase compressive strength.", pack: "5/10/20/230 ltr", color: "Brownish yellow like petrol", features: ["Waterproof Mortar, Plaster and concrete.", "Increase compressive strength & Durability of construction.", "Increase work ability of plaster and concrete", "Resists Corrosion of steel", "Reduce crack developing in concrete and plaster by Reducing its shrinkage."] },
  { slug: "sbr-bond", name: "HIR SBR BOND", image: "/images/product/SBR Bond.png", category: "Waterproofing", short: "HIR SBR BOND is acrylic base liquid for bonding repairing and waterproofing. HIR SBR BOND produce strong bond between old and new plaster, concrete and suitable for all type of cement base repairing.", pack: "250/500gm, 1/5/10kg", color: "White", features: ["UV Resistance", "Improves Elasticity, Flexibility And Tensile Strength", "Easy To Use, Non-toxic", "Inhibits Cracking, Improves Surface Hardening, Limits Wear And Dust Production", "Makes The Mortar Waterproof And Reduces Susceptibility to Acids And Greases"] },
  { slug: "base-coat", name: "HIR BASE COAT", image: "/images/product/Base-Coat.png", category: "Waterproofing", short: "A polymer based high bonding primer used as base chemical applied prior to SUPER COAT waterproofing. It adheres to surface strongly and Provide Better bonding between the substances. Additionally, it also smoothen the surface for friendly application of top coatings. BASE COAT is universal primer for every concrete or cement, tiles and steel surfaces.", pack: "1ltr / 5ltr", color: "White after drying turns clear", features: ["Thickness: 0.1mm", "Touch Dry time: 15minutes", "Tensile strength: 1mm crack bridging", "Compatible with Steel and Cement Surfaces", "Hardness: 38 | Flexible Above -8°C", "Toluene: Softens the material"] },
  { slug: "super-coat", name: "HIR SUPERCOAT", image: "/images/product/Super Coat.png", category: "Waterproofing", short: "A polymer based system consists of cement and emulsion formulated using German Technology for best Waterproofing results. The product passed Global Migration Test for Portable Water Laid down in US_FDA. The Breathable membrane has property of resistance to water vapour to pass through. Membrane is Resistance to Carbon dioxide Diffusion and High Resistant to Chloride lon Penetration", pack: "Part A 5lter + Part B 10kg", coverage: "300sq.ft/20kg/1mm/2coat", color: "Part A Liquid: White and Part B Powder:Grey", features: ["Thickness: 1mm-2mm", "Touch Dry time: 120 minutes.", "Tensile strength: 3-4 N/mm2 Elongation to , brack 30-40% unde water ,1mm to 2mm crack bridging.", ">Flexible Film: 1 C", "MFFT: pH 7.00 - 9.00", "Application:Sandwish structure before laying tiles,granite,marble,etc"] },
  { slug: "nero-coat", name: "HIR NERO COAT", image: "/images/product/Nero Coat.png", category: "Waterproofing", short: "A Water based compound based on Styrene Butadiene copolymer with high bonding primer. A chemical that is applied after SUPER COAT waterproof and form damp-proof membrane.", pack: "2ltr,10ltr", coverage: "300sq.ft/10ltr/250 micron/2coat", color: "Black", features: ["Thickness: 0.3mm", "Toluene: Softens the material", "Tensile strength: 3-4 N/mm2 , Elongation to brack 380% , 1mm to 2mm crack bridging.", "Hardness: 38 Flexible Above -8°C", "Touch Dry time: 15 minutes", "Application: Sandwish structure before laying tiles,granite,marble,etc"] },
  { slug: "heat-x", name: "HIR HEAT-X", image: "/images/product/Heat X.png", category: "Waterproofing", short: "An increasing utilization of Air Conditioning and carbon emission in environment leads to Global Warming. We at HIR with vision to provide solutions to the customers' problem and eco-friendly products.", pack: "1ltr,10ltr", coverage: "300sq.ft/10ltr/250 micron/2coat", color: "White and can be customizable accordion to choice", features: ["Waterproofing", "Temperature Reduction", "Lower Carbon Emission", "Crack Bridging property", "Anti-Dirt pick up", "Light Weight"] },
  { slug: "crack-lock", name: "HIR Crack Lock", image: "/images/product/Crack-lock.png", category: "Waterproofing", short: "CRACK LOCK is an acrylic polymer based white crack filler paste made of acrylic emulsion polymer. It provides a strong bond with flexibility which accommodates the cracks in the plaster and provides a water resistant surface with aesthetic appearance.", pack: "500gm , 1kg", coverage: "NA", color: "White and paintable", features: ["For Internal crack repairs", "For external crack repairs from Hair line to 3 mm in width", "For hair line cracks in painted surfaces that result in internal water leakage"] },
  { slug: "damp-x-primer", name: "HIR DAMP X PRIMER", image: "/images/product/Black-Tile-Primer.png", category: "Waterproofing", short: "HIR Damp X Primer is a fibre reinforced elastomeric liquid applied water proofing membrane. It is formulated with selected elastomeric and resilient acrylic polymers and reinforcing polyester fibers. Upon curing, it forms a thick, seamless, durable membrane thus offering ultimate waterproofing for external walls.", applicationArea: "Exterior surface", pack: "1 ltr & 10 ltr", coverage: "400sq.ft/10ltr/100 micron/2coat", color: "white", features: ["Waterproofing protection of up to 7 bars hydrostatic pressure.", "Unmatched crack bridging ability due to elastomeric properties.", "Reinforced with glass fibres for superior abrasion resistance.", "Strong adhesion to masonry substrates.", "High sheen, brilliant white colour and thick coat results in high levels of heat reflectance.", "Single pack, easy to apply and simple re-coating."] },
  { slug: "shield", name: "HIR SHIELD", image: "/images/product/Shield.png", category: "Waterproofing", short: "SHIELD Product is a white and customized colour, breathable membrane. This product is formulated to waterproof exterior walls.", applicationArea: "Exterior surface", pack: "1lter,10ltr", coverage: "300sq.ft/10ltr/100 micron/2coat", color: "white But Can Be Customize Accordion To Choice", features: ["It has property of Anti dust pick up and Resistance to Algae", "It has better bonding with sheen and shine.", "Shield works as all weather protection for exterior walls with great elongation features.", "Hairline to 1mm cracks filled during application.", "Light Weight", "UV Resistance"] },
  { slug: "salt-x", name: "HIR Salt-X", image: "/images/product/Salt-x.png", category: "Waterproofing", short: "HIR SALT X is high quality Modified Acrylic Polymer base Water Repellent waterproofing master. Due to smaller particle size HIR SALT X deep penetrates and lock pores.", pack: "ltr", coverage: "High porous(red brick) 30-40 Sqft/Litre", color: "Milky White and turns clear after drying", features: ["Note: SURFACE TO BE APPLIED SHOULD BE MINIMUM 6 TO 8 WEEKS AGED (OLD). Do not add water, or other additive can effect the final result.", "SURFACE TO BE APPLIED SHOULD BE MINIMUM 6 TO 8 WEEKS AGED (OLD).", "Do not add water, or other additive can effect the final result."] },
  { slug: "notched-ss-trowel", name: "NOTCHED SS TROWEL", image: "/images/product/TROWEL.png", category: "Tools & Accessories", short: "A special trowel named 'Notched Trowel' has to be used for applying the tile adhesives (refer the below picture). The Notched Trowels come in various sizes, typically 6mm, 8mm, 10mm, 15mm etc.," },
  { slug: "tiles-spacer", name: "HIR Tiles Spacers", image: "/images/product/spacers.png", category: "Tools & Accessories", short: "A special trowel named 'Notched Trowel' has to be used for applying the tile adhesives (refer the below picture). The Notched Trowels come in various sizes, typically 6mm, 8mm, 10mm, 15mm etc.,", features: ["Since the minor dimensional variation is possible in tiles, spacer joint helps in camouflage those variations.", "Spacer joints will be filled with the suitable grout.", "Replacing damaged tile is easy, because we can remove the particular tile without damaging the nearest tiles.", "Spacer joint is used for the purpose of uniformity in tile joints and for better finish; Aesthetic appearance also improves."] },
  { slug: "tiles-levelling-plier", name: "HIR Plier", image: "/images/product/Plier.png", category: "Tools & Accessories", short: "Tile Levelling System are reusable, durable, wear-resistant and perfect for DIY operations, it was easy enough to fix or remove with Special wrench, Save your money." },
];

export const categories = [
  "Tiles & Stone Solutions",
  "Wall Solutions",
  "Grouts & Sealants",
  "Waterproofing",
  "Tools & Accessories",
] as const;

export type Blog = {
  slug: string; title: string; image: string; excerpt: string;
  sections: { heading: string; body?: string; list?: string[] }[];
};

export const blogs: Blog[] = [
  {
    slug: "choosing-the-right-tile-adhesive",
    title: "Choosing the Right Tile Adhesive for Your Project",
    image: "/images/tiles adhesive.jpg",
    excerpt: "When selecting tile adhesive, consider the type of tiles and the surface. Cement-based adhesives are ideal for ceramic and porcelain tiles,...",
    sections: [
      { heading: "Choosing the Right Tile Adhesive for Your Project", body: "When selecting tile adhesive, consider the type of tiles and the surface. Cement-based adhesives are ideal for ceramic and porcelain tiles, while epoxy adhesives offer superior bonding for glass tiles and mosaics. Always check the manufacturer's recommendations for best results." },
      { heading: "Application Tips for Tile Adhesive", list: ["Ensure the surface is clean, dry, and level before applying tile adhesive.", "Use a notched trowel to spread the adhesive evenly.", "Press tiles firmly into place and twist slightly to secure.", "Allow adequate curing time before grouting."] },
      { heading: "Tile Adhesive for Different Environments", list: ["For wet areas like bathrooms and kitchens, use a waterproof tile adhesive to prevent moisture damage.", "In high-traffic areas, choose a high-strength adhesive to ensure long-lasting durability.", "Temperature variations? Opt for flexible adhesives to avoid cracking."] },
    ],
  },
  {
    slug: "why-choose-epoxy-grout",
    title: "Why Choose Epoxy Grout?",
    image: "/images/epoxy grout .avif",
    excerpt: "Epoxy grout is a superior choice for tile installations due to its durability, stain resistance, and...",
    sections: [
      { heading: "Why Choose Epoxy Grout?", body: "Epoxy grout is a superior choice for tile installations due to its durability, stain resistance, and waterproof properties. It's ideal for areas exposed to moisture, such as kitchens, bathrooms, and swimming pools." },
      { heading: "Applying Epoxy Grout: Tips for Success", list: ["Mix epoxy grout thoroughly according to the manufacturer's instructions.", "Apply with a rubber float, pressing firmly into joints.", "Remove excess grout quickly with a damp sponge, as epoxy hardens faster than cement-based grout.", "Allow curing for at least 24 hours."] },
      { heading: "Maintaining Epoxy Grout", list: ["Epoxy grout is low maintenance but benefits from regular cleaning with a mild detergent to retain its appearance.", "Avoid abrasive cleaners that could dull the surface.", "For stubborn stains, use a solution of water and vinegar or a specialized epoxy grout cleaner."] },
    ],
  },
  {
    slug: "importance-of-waterproofing",
    title: "Importance of Waterproofing in Construction",
    image: "/images/water proffing.jpg",
    excerpt: "Waterproofing is crucial to protect structures from water damage, mold, and structural deterioration. ...",
    sections: [
      { heading: "Importance of Waterproofing in Construction", body: "Waterproofing is crucial to protect structures from water damage, mold, and structural deterioration. It extends the life of buildings and enhances comfort by preventing leaks and dampness." },
      { heading: "Types of Waterproofing Methods", body: "Popular waterproofing methods include liquid membranes, bituminous coatings, and polyurethane liquid membranes. Liquid membranes offer seamless coverage, while bituminous coatings are cost-effective. Polyurethane membranes provide high elasticity and durability." },
      { heading: "Steps to Effective Waterproofing", body: "Start by cleaning and preparing the surface. Apply a primer to improve adhesion, then apply the chosen waterproofing material in layers. Ensure each layer cures before applying the next. Pay extra attention to joints, corners, and seams for complete protection." },
    ],
  },
];

export const faqs = [
  { q: "What is the difference between tile adhesive and regular mortar?", a: "Tile adhesive is a specialized bonding agent specifically designed for adhering tiles to substrates, offering stronger and more durable adhesion compared to traditional mortar." },
  { q: "How do I choose the right tile adhesive for my project?", a: "Consider factors such as the type of tiles being used, substrate material, environmental conditions, and application method. Consult with a professional or refer to manufacturer guidelines for specific recommendations." },
  { q: "Can tile adhesive be used for outdoor applications?", a: "Yes, there are tile adhesives formulated specifically for outdoor use, capable of withstanding exposure to moisture, temperature fluctuations, and other environmental factors." },
  { q: "What are the advantages of epoxy grout over traditional grout?", a: "Epoxy grout is highly resistant to stains, chemicals, and water, making it ideal for areas prone to moisture or high traffic. It also offers superior durability and color consistency compared to traditional cement-based grouts." },
  { q: "How do I prevent water leakage in my bathroom or basement?", a: "Proper waterproofing is essential. Utilize waterproofing membranes or coatings on surfaces prone to water exposure, such as shower walls, bathroom floors, and basement walls. Ensure all joints and seams are properly sealed with waterproofing products." },
  { q: "Can waterproofing products be applied to existing structures?", a: "Yes, many waterproofing products are designed for both new construction and retrofit applications. However, surface preparation and compatibility with existing materials should be considered before application." },
  { q: "What is the typical lifespan of waterproofing treatments?", a: "The lifespan of waterproofing treatments varies depending on factors such as product quality, application method, environmental conditions, and maintenance. Generally, quality waterproofing products can provide protection for several years with proper installation and upkeep." },
  { q: "Are there any special precautions to take during the application of these products?", a: "Follow manufacturer instructions carefully, including surface preparation, application techniques, curing times, and safety precautions. Proper ventilation and personal protective equipment may be necessary, especially when working with epoxy products or waterproofing chemicals." },
];

export const testimonials = [
  { title: "Review of HIR tile adhesive, HIR epoxy grout and HIR waterproofing products by Prestigious Dealer", videoId: "nqWAo-Exh3Q" },
  { title: "HIR Royal-O-Seal Review: Ultimate Solution for Leakage-Proof Bathrooms, Walls & More. Builder's Guide", videoId: "0m_Y_g2Eks4" },
  { title: "Genuine Review by Mr. Vipul: HIR Tile Adhesive, Epoxy Grout, Waterproofing & AAC Block adhesive", videoId: "Zf7BF4jdC1g" },
];

export const historyVideoId = "Z4RhfoREu6I";

export const contact = {
  phone: "1800 572 2779",
  phoneHref: "tel:18005722779",
  whatsapp: "+919904821334",
  whatsappHref: "https://api.whatsapp.com/send?phone=919904821334&text=Hello%2C%20I%20would%20like%20to%20know%20more%20about%20HIR%20products.",
  email: "info@hirgroup.in",
  address: "HIR Industries C/O Gauri Ceramics Compound, Opp. Sahkari Jin, On National Highway Road-8, Himatnagar 383 001, Gujarat, India",
};

export const socialLinks = [
  { label: "Facebook", href: "https://www.facebook.com/hir.india?mibextid=LQQJ4d", icon: "/images/facebook.svg" },
  { label: "Instagram", href: "https://www.instagram.com/hir.india?igsh=MWVua2xkbmg2aHJzMw%3D%3D", icon: "/images/insta.svg" },
  { label: "LinkedIn", href: "https://www.linkedin.com/in/hir-your-building-master-5a96511b1/", icon: "/images/indeed.svg" },
  { label: "YouTube", href: "https://www.youtube.com/@HIRindustries", icon: "/images/youtube.svg" },
];
