/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapBlogsDotxmlRouteImport } from './routes/sitemap-blogs[.]xml'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapProductsDotxmlRouteImport } from './routes/sitemap-products[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminCatalogueRouteImport } from './routes/admin.catalogue'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ApiPublicPdfSplatRouteImport } from './routes/api/public/pdf.$'
import { Route as ApiPublicImagesBucketFilenameRouteImport } from './routes/api/public/images.$bucket.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogsDotxmlRoute = SitemapBlogsDotxmlRouteImport.update({
  id: '/sitemap-blogs.xml',
  path: '/sitemap-blogs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsDotxmlRoute = SitemapProductsDotxmlRouteImport.update({
  id: '/sitemap-products.xml',
  path: '/sitemap-products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueRoute = AdminCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPdfSplatRoute = ApiPublicPdfSplatRouteImport.update({
  id: '/api/public/pdf/$',
  path: '/api/public/pdf/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImagesBucketFilenameRoute =
  ApiPublicImagesBucketFilenameRouteImport.update({
    id: '/api/public/images/$bucket/$filename',
    path: '/api/public/images/$bucket/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/sitemap-blogs.xml': typeof SitemapBlogsDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/public/pdf/$': typeof ApiPublicPdfSplatRoute
  '/api/public/images/$bucket/$filename': typeof ApiPublicImagesBucketFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/sitemap-blogs.xml': typeof SitemapBlogsDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/public/pdf/$': typeof ApiPublicPdfSplatRoute
  '/api/public/images/$bucket/$filename': typeof ApiPublicImagesBucketFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/sitemap-blogs.xml': typeof SitemapBlogsDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/public/pdf/$': typeof ApiPublicPdfSplatRoute
  '/api/public/images/$bucket/$filename': typeof ApiPublicImagesBucketFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/calculator'
    | '/contact'
    | '/sitemap-blogs.xml'
    | '/sitemap-images.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/visualizer'
    | '/admin/blogs'
    | '/admin/catalogue'
    | '/admin/products'
    | '/admin/seo'
    | '/blogs/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/blogs/'
    | '/products/'
    | '/api/public/pdf/$'
    | '/api/public/images/$bucket/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/contact'
    | '/sitemap-blogs.xml'
    | '/sitemap-images.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/visualizer'
    | '/admin/blogs'
    | '/admin/catalogue'
    | '/admin/products'
    | '/admin/seo'
    | '/blogs/$slug'
    | '/products/$slug'
    | '/admin'
    | '/blogs'
    | '/products'
    | '/api/public/pdf/$'
    | '/api/public/images/$bucket/$filename'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/calculator'
    | '/contact'
    | '/sitemap-blogs.xml'
    | '/sitemap-images.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/visualizer'
    | '/admin/blogs'
    | '/admin/catalogue'
    | '/admin/products'
    | '/admin/seo'
    | '/blogs/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/blogs/'
    | '/products/'
    | '/api/public/pdf/$'
    | '/api/public/images/$bucket/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  SitemapBlogsDotxmlRoute: typeof SitemapBlogsDotxmlRoute
  SitemapImagesDotxmlRoute: typeof SitemapImagesDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapProductsDotxmlRoute: typeof SitemapProductsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisualizerRoute: typeof VisualizerRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPublicPdfSplatRoute: typeof ApiPublicPdfSplatRoute
  ApiPublicImagesBucketFilenameRoute: typeof ApiPublicImagesBucketFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blogs.xml': {
      id: '/sitemap-blogs.xml'
      path: '/sitemap-blogs.xml'
      fullPath: '/sitemap-blogs.xml'
      preLoaderRoute: typeof SitemapBlogsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-images.xml': {
      id: '/sitemap-images.xml'
      path: '/sitemap-images.xml'
      fullPath: '/sitemap-images.xml'
      preLoaderRoute: typeof SitemapImagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products.xml': {
      id: '/sitemap-products.xml'
      path: '/sitemap-products.xml'
      fullPath: '/sitemap-products.xml'
      preLoaderRoute: typeof SitemapProductsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue': {
      id: '/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AdminCatalogueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pdf/$': {
      id: '/api/public/pdf/$'
      path: '/api/public/pdf/$'
      fullPath: '/api/public/pdf/$'
      preLoaderRoute: typeof ApiPublicPdfSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/images/$bucket/$filename': {
      id: '/api/public/images/$bucket/$filename'
      path: '/api/public/images/$bucket/$filename'
      fullPath: '/api/public/images/$bucket/$filename'
      preLoaderRoute: typeof ApiPublicImagesBucketFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCatalogueRoute: typeof AdminCatalogueRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCatalogueRoute: AdminCatalogueRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  SitemapBlogsDotxmlRoute: SitemapBlogsDotxmlRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapProductsDotxmlRoute: SitemapProductsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisualizerRoute: VisualizerRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPublicPdfSplatRoute: ApiPublicPdfSplatRoute,
  ApiPublicImagesBucketFilenameRoute: ApiPublicImagesBucketFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
